services:
  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=desafio-07
      - POSTGRES_PASSWORD=desafio-07
      - POSTGRES_DB=desafio-07-db-v1
    volumes:
      - desafio-07-pg-db:/postgres

volumes:
  desafio-07-pg-db:
